version: '2'
services:
  web:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-clock-panel,jdbranham-diagram-panel
    depends_on:
      - "influx_data"
    volumes:
      - tinflux-volume:/var/lib/grafana
  influx_data:
    image: "influxdb"
    volumes:
      - tinflux-volume:/var/lib/influxdb
  influx_setup:
    image: "airedale/tintri_pulldata"
    depends_on:
      - "influx_data"
    env_file: 
      - influx_setup.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external:
      name: tinflux
volumes:
  tinflux-volume:
